### ISSUE TITLE
Move sequence reference extensions to sequence reference file

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/va-spec#114]
@larrybabb I think the following extensions belong on a sequenceReference object, not a variation object.

https://github.com/ga4gh/va-spec/blob/c7f937a3998f02d10568b27ef74ab00a7269f447/examples/clinvar_data/ctxvars-mvp.jsonc#L82C1-L97C15

**Comment by larrybabb** [comment]
the assembly and accession can definitely go there. I don't think there's a mandate where we put extensions (it's a matter of "put it where you want" ).  But the "cyto" location should not go on the SeqRef maybe the Location object would be the most granular place to put that (since it depicts the region and not the entire sequence).

I can try to put these on the appropriate objects so that folks don't get lulled into thinking these will exist at the higher levels of the object tree.
