### ISSUE TITLE
Keep 'proposition' property and 'Proposition' class in the v1 core-im-source yaml release?

### ISSUE THREAD

**Issue by mbrush** [ga4gh/va-spec#133]
The last VA ‘community' decision was to use `Propositions` as the standard/normalized way to compartmentalize and explicitly express semantics of Statements.  This was back when ClinGen and VICC planned to use them in their models. Accordingly, these were included in the latest iteration of VA Core IM models and examples. 

However, ClinGen/VICC have since chosen not to utilize `Propositions` in their latest implementation profile work. Instead, Larry/Alex flattened SPOQ properties into the Core IM Statement Class, and used these within specialized Statement classes in Profiles to capture statement semantics. 

I have included the `Proposition` class in the latest version of the core-im-source.yaml file – because:
- I think the notion of a "proposition" is useful and central to the VA/SEPIO model, and useful to include in the model even if adopters choose to flatten its SPOQ properties into the `Statement` object for structural simplicity.  (Note that I have included SPOQ properties in the statement class as well, to formally allow for this).
- I rely on the notion of a Proposition in defining many other classes and properties, and it is a useful to define a class for this idea that consumers can reference in the schema.
- I want to document the thought that went into modeling Propositions, and the utility they can provide, to advertise this modeling pattern for potential adopters who may benefit form it. Esp given its centrality to how VA data is to be _understood_ (even if it is not central ti existing implementations). 
- The `Proposition` class has utility for representation of Evidence Lines as well (esp when they are captured independently of the Statements they support). Again, no implementations currently use this pattern, but it seemed potentially relevant to  some that were discussed at the last Connect meeting.

As noted, I recognize that at present there are no implementers with use cases requiring Propositions (either to compartmentalize Statement semantics, or explicitly capture what evidence lines are evaluated against). So we could choose not to include `Propositions` in the v1 core-im-source yaml file, and instead manually draft a RTD page that explains meaning and utility of this Class. This would keep the source yaml schema itself simpler and avoid any confusion that a `Proposition` class may cause. Thoughts?

**Comment by larrybabb** [comment]
@mbrush I'm not sure what this issue is here? 

Based on our maturity model process the `Proposition` class has ever right to be in the core-im-source.yaml in `draft` maturity mode.  

If you are suggesting that no class should be added to any of the specs until an implementer *vouches* for it with the intention and concrete plan to use it, then maybe we should rethink putting it in, but I'm not sure our process is that restrictive (we should clarify that though).

I don't if/when `Proposition` will ever move to an approved product standard as it would need to go through `trial use` and `normative` in several implementations first, but if it is something that the VA community truly wants and more importantly needs then this should happen in time.

Related note: We do all need to get through a full MM process where classes move up the maturity modes and eventually get to `trial use` so that these can then be collected and proposed for product approval at which time they would become `normative`.  Once we all experience this we should then be able to understand how to deal with *ideals* vs *needs*.

**Comment by larrybabb** [comment]
@mbrush if you are fine with the fact that `Proposition` is in the core-im as `draft` for the time being, feel free to close this issue. If there is a more distinct concern that needs addressing, please clarify.
