### ISSUE TITLE
Allowed types of propositions for VariationNeoplasmTherapeuticResponseStatement.target_propositions property

### ISSUE THREAD

**Issue by viveknuthalapati** [ga4gh/va-spec#98]
Does it make sense to allow [target_proposition](https://github.com/ga4gh/va-spec/blob/metakb-cvc/schema/annotation.json#L450) under the [VariationNeoplasmTherapeuticResponseStatement](https://github.com/ga4gh/va-spec/blob/metakb-cvc/schema/annotation.json#L384)  to be of type [VariationGermlinePathogenicityProposition ](https://github.com/ga4gh/va-spec/blob/metakb-cvc/schema/annotation.json#L537)?

https://github.com/ga4gh/va-spec/blob/4fd8a1a07f274b6d8e19f7c69d0de0d912282e3b/schema/annotation.json#L453

**Comment by larrybabb** [comment]
@viveknuthalapati In the current 1.x branch @ahwagner moved away from using `target_proposition` altogether. So I'm going to close this issue since it is no longer relevant. 

If however, you want @ahwagner to clarify whether or not a `VariationGermlinePathogenicityProposition` could be the backing proposition behind a `VariationTherapeuticResponseStatement`, then please re-open and tag @ahwagner for that question.  From my limited understanding it doesn't make any sense, but I find my assumptions are often wrong.
